version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - .:/app
      - /app/node_modules

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: event_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
